### ISSUE TITLE
chart.pieLabel is not a function

### ISSUE THREAD

**Issue by eruca** [tarojsx/library#4]
```jsx
import React, { CSSProperties, useCallback } from "react";
import { F2 } from "@tarojsx/library/dist/antv";

export interface PieInputType {
    name: string;
    count: number;
    group: string;
}

interface IPie {
    data: PieInputType[];
    radius?: number;
    style?: CSSProperties;
}

export default function Pie({
    data = [],
    radius = 0.85,
    style = { width: "100vw", height: "50vh" },
}: IPie) {
    return (
        <F2 style={style} data={data}>
            {({ chart, data }) => {
                chart.source(data);

                chart.legend(false);
                chart.axis(false);
                chart.tooltip(false);

                chart.coord("polar", {
                    transposed: true,
                    radius,
                });

                chart.pieLabel({
                    sidePadding: 40,
                    label1: (data, color) => ({
                        text: data.name.toUpperCase(),
                        fill: color,
                    }),
                    label2: (data) => ({
                        text: String(data.count),
                        fill: "$808080",
                        fontWeight: "bold",
                    }),
                });

                chart
                    .interval()
                    .position("group*count")
                    .color("name")
                    .adjust("stack");
                chart.render();
            }}
        </F2>
    );
}
```

发生下面的错误？
```bash
(in promise) MiniProgramError
chart.pieLabel is not a function
TypeError: chart.pieLabel is not a function
    at http://127.0.0.1:12752/appservice/pages/records/graph/index.js:19974:11
    at _callee$ (http://127.0.0.1:12752/appservice/pages/records/graph/index.js:17907:15)
    at tryCatch (http://127.0.0.1:12752/appservice/pages/records/graph/index.js:18633:40)
    at Generator.invoke [as _invoke] (http://127.0.0.1:12752/appservice/pages/records/graph/index.js:18867:22)
    at Generator.prototype.<computed> [as next] (http://127.0.0.1:12752/appservice/pages/records/graph/index.js:18685:21)
    at asyncGeneratorStep (http://127.0.0.1:12752/appservice/pages/records/graph/index.js:17715:24)
    at _next (http://127.0.0.1:12752/appservice/pages/records/graph/index.js:17737:9)
```

可是官方文档:
https://f2.antv.vision/en/examples/pie/basic#labelline-pie可以啊？

**Comment by cncolder** [comment]
官方文档没更新. 现在 PieLabel 是按需加载的插件.

https://f2.antv.vision/en/docs/api/chart/pie-label
https://codesandbox.io/s/wizardly-moon-4eb16?file=/index.js

```js
import F2 from '@antv/f2'
import PieLabel from '@antv/f2/lib/plugin/pie-label'

F2.Chart.plugins.register(PieLabel)
```

**Comment by eruca** [comment]
怎么在library里使用？可以使用吗？

**Comment by cncolder** [comment]
> 怎么在library里使用？可以使用吗？

上面这样 register 之后全局生效，因为 import 的 antv f2 是唯一的，无论从哪里导入都是同一个对象。
